name: wagtail-content-import CI

on:
  push:
    branches:
      - main
      - master
      - 'stable/**'

  pull_request:

jobs:
  test-sqlite:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']
        django: ['3.2', '4.0', '4.1']
        wagtail: ['4.1', '4.2']
        include:
          - python: '3.11'
            django: '4.1'
            wagtail: '4.1'
          - python: '3.11'
            django: '4.1'
            wagtail: '4.2'

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-sqlite

  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8
        uses: actions/setup-python@v4
        with:
          python-version: 3.8
      - name: Install flake8
        run: |
          python -m pip install flake8
      - name: flake8
        run: |
          flake8 .
      - name: Install isort
        run: |
          python -m pip install isort
      - name: isort
        run: |
          isort .

  test-postgres:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.8', '3.9', '3.10']
        django: ['3.2', '4.0', '4.1']
        wagtail: ['4.1', '4.2']
        postgres: ['15']
        include:
          - python: '3.11'
            django: '4.1'
            wagtail: '4.1'
            postgres: '15'
          - python: '3.11'
            django: '4.1'
            wagtail: '4.2'
            postgres: '15'

    services:
      postgres:
        image: postgres:${{ matrix.postgres }}
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: |
          python -m pip install tox
      - name: Test
        run: |
          tox
        env:
          DATABASE_URL: postgres://postgres:postgres@localhost:${{ job.services.postgres.ports[5432] }}
          TOXENV: python${{ matrix.python }}-django${{ matrix.django }}-wagtail${{ matrix.wagtail }}-postgres